version: '3.4'

services:
  staticroutes:
    image: staticroutes-dev
    container_name: staticroutes-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
