version: '3.4'

services:
  staticroutes-dev:
    image: staticroutes-dev
    container_name: staticroutes-dev
    hostname: staticroutes-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    stdin_open: true

volumes:
  node_modules:
