version: '3.4'

services:
  staticroutes-test:
    image: staticroutes-dev
    container_name: staticroutes-test
    hostname: staticroutes-test
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: test
    ports:
      - 8080:8080
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "test"]

volumes:
  node_modules:
