name: Test Suite

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm ci
      - name: Run jest test suite
        run: npm run test:ci

      - name: Tests Passed
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}"/actions/runs/${{ github.run_id }}"
          }'

      - name: Tests Failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}"/actions/runs/${{ github.run_id }}"
          }'
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Linters
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npx eslint .

      - name: Linting Passed
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "lint",
            "state": "success",
            "description": "Linting passed",
            "target_url": "https://github.com/${{ github.repository }}"/actions/runs/${{ github.run_id }}"
          }'

      - name: Linting Failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "lint",
            "state": "failure",
            "description": "Linting failed",
            "target_url": "https://github.com/${{ github.repository }}"/actions/runs/${{ github.run_id }}"
          }'
